name: easy_infinite_pagination
description: "The Easy Infinite Pagination package provides a simple and customizable way to implement infinite pagination in your Flutter applications."
version: 0.0.2
homepage: 'https://github.com/FadyFayezYounan/easy_infinite_pagination.git'

topics:
  - list-view
  - pagination
  - infinite
  - scrolling
  - grid-view

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:


